name: Offline Changelog

on:
  release:
    types:
      - published

jobs:
  chanagelog-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Change changelog 
        run: echo "change dunring run" >> changes
      - name: Change changelog1 
        run: cat changes CHANGELOG.md > CHANGELOG.md 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update Offline Changelog"
          branch: offline_changelog
          delete-branch: true
          base: master
          token: ${{ secrets.GITHUB_TOKEN }}
